/** App data keys mirrored to the cloud (not auth/session). */
export const CLOUD_SYNC_KEYS = [
  'trademindpro_trades_v1',
  'trademindpro_reviews_v1',
  'trademindpro_paper_v1',
  'trademindpro_paper_settings_v1',
  'trademindpro_nejoic_v1',
  'trademindpro_nejoic_last_tg_decision',
  'trademindpro_jimbo_v1',
  'trademindpro_blink_v1',
  'trademindpro_scan_settings_v2',
  'trademindpro_scanner_module_v1',
  'trademindpro_scan_history_v1',
  'trademindpro_watchlists_v1',
  'trademindpro_risk_v1',
  'trademindpro_alerts_v1',
  'trademindpro_holdings_v1',
  'trademindpro_strategies_v1',
  'trademindpro_strategy_builder_v1',
  'trademindpro_backtests_v1',
  'trademindpro_backtest_settings_v1',
  'trademindpro_options_scanner_settings_v1',
  'trademindpro_telegram_bot_v1',
  'trademindpro_broker_v1',
  'trademindpro_upstox_token_v1',
  'trademindpro_upstox_connected_at_v1',
  'trademindpro_upstox_extended_v1',
  'trademindpro_ai_agents_v1',
  'trademindpro_ai_chat_v1',
  'trademindpro_ai_activity_v1',
  'trademindpro_ai_last_run_v1',
  'trademindpro_sidebar_collapsed',
] as const;
