/**
 * NSE equity F&O underlyings — sole Jimbo watchlist + CCI scan universe.
 * Live equity LTPs refresh in Jimbo; CCI setups filter this list and attach live ATM option premiums.
 */

export type JimboFoStock = {
  symbol: string;
  name: string;
  lotSize: number;
};

/** Full NSE stock F&O watchlist (equity derivatives underlyings). */
export const NSE_EQUITY_FO_WATCHLIST: JimboFoStock[] = [
  { symbol: 'AARTIIND', name: 'Aarti Industries', lotSize: 850 },
  { symbol: 'ABB', name: 'ABB India', lotSize: 125 },
  { symbol: 'ABBOTINDIA', name: 'Abbott India', lotSize: 40 },
  { symbol: 'ABCAPITAL', name: 'Aditya Birla Capital', lotSize: 3100 },
  { symbol: 'ABFRL', name: 'Aditya Birla Fashion', lotSize: 2600 },
  { symbol: 'ACC', name: 'ACC', lotSize: 300 },
  { symbol: 'ADANIENT', name: 'Adani Enterprises', lotSize: 300 },
  { symbol: 'ADANIGREEN', name: 'Adani Green Energy', lotSize: 600 },
  { symbol: 'ADANIPORTS', name: 'Adani Ports', lotSize: 400 },
  { symbol: 'ALKEM', name: 'Alkem Laboratories', lotSize: 125 },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements', lotSize: 900 },
  { symbol: 'ANGELONE', name: 'Angel One', lotSize: 250 },
  { symbol: 'APLAPOLLO', name: 'APL Apollo Tubes', lotSize: 350 },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals', lotSize: 125 },
  { symbol: 'ASHOKLEY', name: 'Ashok Leyland', lotSize: 2500 },
  { symbol: 'ASIANPAINT', name: 'Asian Paints', lotSize: 200 },
  { symbol: 'ASTRAL', name: 'Astral', lotSize: 275 },
  { symbol: 'ATUL', name: 'Atul', lotSize: 75 },
  { symbol: 'AUBANK', name: 'AU Small Finance Bank', lotSize: 1000 },
  { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma', lotSize: 550 },
  { symbol: 'AXISBANK', name: 'Axis Bank', lotSize: 625 },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto', lotSize: 75 },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv', lotSize: 500 },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance', lotSize: 125 },
  { symbol: 'BALKRISIND', name: 'Balkrishna Industries', lotSize: 200 },
  { symbol: 'BANDHANBNK', name: 'Bandhan Bank', lotSize: 1800 },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda', lotSize: 2925 },
  { symbol: 'BATAINDIA', name: 'Bata India', lotSize: 375 },
  { symbol: 'BEL', name: 'Bharat Electronics', lotSize: 2850 },
  { symbol: 'BERGEPAINT', name: 'Berger Paints', lotSize: 550 },
  { symbol: 'BHARATFORG', name: 'Bharat Forge', lotSize: 500 },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel', lotSize: 475 },
  { symbol: 'BHEL', name: 'BHEL', lotSize: 2625 },
  { symbol: 'BIOCON', name: 'Biocon', lotSize: 2300 },
  { symbol: 'BOSCHLTD', name: 'Bosch', lotSize: 25 },
  { symbol: 'BPCL', name: 'BPCL', lotSize: 1800 },
  { symbol: 'BRITANNIA', name: 'Britannia', lotSize: 125 },
  { symbol: 'BSOFT', name: 'Birlasoft', lotSize: 900 },
  { symbol: 'CAMS', name: 'CAMS', lotSize: 150 },
  { symbol: 'CANBK', name: 'Canara Bank', lotSize: 6750 },
  { symbol: 'CHAMBLFERT', name: 'Chambal Fertilisers', lotSize: 950 },
  { symbol: 'CHOLAFIN', name: 'Cholamandalam Finance', lotSize: 625 },
  { symbol: 'CIPLA', name: 'Cipla', lotSize: 650 },
  { symbol: 'COALINDIA', name: 'Coal India', lotSize: 1350 },
  { symbol: 'COFORGE', name: 'Coforge', lotSize: 75 },
  { symbol: 'COLPAL', name: 'Colgate-Palmolive', lotSize: 200 },
  { symbol: 'CONCOR', name: 'Container Corporation', lotSize: 625 },
  { symbol: 'COROMANDEL', name: 'Coromandel International', lotSize: 350 },
  { symbol: 'CROMPTON', name: 'Crompton Greaves Consumer', lotSize: 1800 },
  { symbol: 'CUB', name: 'City Union Bank', lotSize: 2500 },
  { symbol: 'CUMMINSIND', name: 'Cummins India', lotSize: 300 },
  { symbol: 'DABUR', name: 'Dabur India', lotSize: 1250 },
  { symbol: 'DALBHARAT', name: 'Dalmia Bharat', lotSize: 250 },
  { symbol: 'DEEPAKNTR', name: 'Deepak Nitrite', lotSize: 200 },
  { symbol: 'DELHIVERY', name: 'Delhivery', lotSize: 1225 },
  { symbol: 'DIVISLAB', name: "Divi's Laboratories", lotSize: 100 },
  { symbol: 'DIXON', name: 'Dixon Technologies', lotSize: 100 },
  { symbol: 'DLF', name: 'DLF', lotSize: 825 },
  { symbol: 'DRREDDY', name: "Dr Reddy's", lotSize: 125 },
  { symbol: 'EICHERMOT', name: 'Eicher Motors', lotSize: 175 },
  { symbol: 'ESCORTS', name: 'Escorts Kubota', lotSize: 150 },
  { symbol: 'EXIDEIND', name: 'Exide Industries', lotSize: 1800 },
  { symbol: 'FEDERALBNK', name: 'Federal Bank', lotSize: 5000 },
  { symbol: 'GAIL', name: 'GAIL', lotSize: 3150 },
  { symbol: 'GLENMARK', name: 'Glenmark Pharma', lotSize: 375 },
  { symbol: 'GMRINFRA', name: 'GMR Airports', lotSize: 11250 },
  { symbol: 'GNFC', name: 'GNFC', lotSize: 650 },
  { symbol: 'GODREJCP', name: 'Godrej Consumer', lotSize: 500 },
  { symbol: 'GODREJPROP', name: 'Godrej Properties', lotSize: 325 },
  { symbol: 'GRANULES', name: 'Granules India', lotSize: 1000 },
  { symbol: 'GRASIM', name: 'Grasim', lotSize: 250 },
  { symbol: 'HAL', name: 'Hindustan Aeronautics', lotSize: 150 },
  { symbol: 'HAVELLS', name: 'Havells India', lotSize: 500 },
  { symbol: 'HCLTECH', name: 'HCL Tech', lotSize: 350 },
  { symbol: 'HDFCAMC', name: 'HDFC AMC', lotSize: 150 },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', lotSize: 550 },
  { symbol: 'HDFCLIFE', name: 'HDFC Life', lotSize: 1100 },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp', lotSize: 150 },
  { symbol: 'HFCL', name: 'HFCL', lotSize: 5150 },
  { symbol: 'HINDALCO', name: 'Hindalco', lotSize: 1400 },
  { symbol: 'HINDCOPPER', name: 'Hindustan Copper', lotSize: 1700 },
  { symbol: 'HINDPETRO', name: 'HPCL', lotSize: 1350 },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', lotSize: 300 },
  { symbol: 'IDEA', name: 'Vodafone Idea', lotSize: 70000 },
  { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank', lotSize: 7500 },
  { symbol: 'IEX', name: 'Indian Energy Exchange', lotSize: 1875 },
  { symbol: 'IGL', name: 'Indraprastha Gas', lotSize: 1375 },
  { symbol: 'INDHOTEL', name: 'Indian Hotels', lotSize: 1000 },
  { symbol: 'INDIAMART', name: 'IndiaMART', lotSize: 150 },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation', lotSize: 300 },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank', lotSize: 500 },
  { symbol: 'INDUSTOWER', name: 'Indus Towers', lotSize: 1400 },
  { symbol: 'INFY', name: 'Infosys', lotSize: 400 },
  { symbol: 'IOC', name: 'Indian Oil', lotSize: 4875 },
  { symbol: 'IRCTC', name: 'IRCTC', lotSize: 875 },
  { symbol: 'ITC', name: 'ITC', lotSize: 1600 },
  { symbol: 'JINDALSTEL', name: 'Jindal Steel', lotSize: 625 },
  { symbol: 'JIOFIN', name: 'Jio Financial', lotSize: 2900 },
  { symbol: 'JSWENERGY', name: 'JSW Energy', lotSize: 1000 },
  { symbol: 'JSWSTEEL', name: 'JSW Steel', lotSize: 675 },
  { symbol: 'JUBLFOOD', name: 'Jubilant FoodWorks', lotSize: 625 },
  { symbol: 'KALYANKJIL', name: 'Kalyan Jewellers', lotSize: 1175 },
  { symbol: 'KEI', name: 'KEI Industries', lotSize: 175 },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', lotSize: 400 },
  { symbol: 'LALPATHLAB', name: 'Dr Lal PathLabs', lotSize: 300 },
  { symbol: 'LAURUSLABS', name: 'Laurus Labs', lotSize: 1100 },
  { symbol: 'LICHSGFIN', name: 'LIC Housing Finance', lotSize: 1000 },
  { symbol: 'LICI', name: 'LIC of India', lotSize: 700 },
  { symbol: 'LODHA', name: 'Macrotech Developers', lotSize: 450 },
  { symbol: 'LT', name: 'Larsen & Toubro', lotSize: 150 },
  { symbol: 'LTIM', name: 'LTIMindtree', lotSize: 150 },
  { symbol: 'LTTS', name: 'L&T Technology Services', lotSize: 100 },
  { symbol: 'LUPIN', name: 'Lupin', lotSize: 425 },
  { symbol: 'M&M', name: 'Mahindra & Mahindra', lotSize: 200 },
  { symbol: 'M&MFIN', name: 'M&M Financial', lotSize: 800 },
  { symbol: 'MANAPPURAM', name: 'Manappuram Finance', lotSize: 3000 },
  { symbol: 'MARICO', name: 'Marico', lotSize: 1200 },
  { symbol: 'MARUTI', name: 'Maruti Suzuki', lotSize: 50 },
  { symbol: 'MAXHEALTH', name: 'Max Healthcare', lotSize: 650 },
  { symbol: 'MCX', name: 'MCX', lotSize: 125 },
  { symbol: 'METROPOLIS', name: 'Metropolis Healthcare', lotSize: 300 },
  { symbol: 'MFSL', name: 'Max Financial', lotSize: 650 },
  { symbol: 'MGL', name: 'Mahanagar Gas', lotSize: 400 },
  { symbol: 'MOTHERSON', name: 'Samvardhana Motherson', lotSize: 3350 },
  { symbol: 'MPHASIS', name: 'Mphasis', lotSize: 275 },
  { symbol: 'MRF', name: 'MRF', lotSize: 5 },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance', lotSize: 275 },
  { symbol: 'NATIONALUM', name: 'NALCO', lotSize: 3750 },
  { symbol: 'NAUKRI', name: 'Info Edge', lotSize: 375 },
  { symbol: 'NAVINFLUOR', name: 'Navin Fluorine', lotSize: 100 },
  { symbol: 'NESTLEIND', name: 'Nestle India', lotSize: 25 },
  { symbol: 'NMDC', name: 'NMDC', lotSize: 2250 },
  { symbol: 'NTPC', name: 'NTPC', lotSize: 1500 },
  { symbol: 'NYKAA', name: 'Nykaa', lotSize: 3050 },
  { symbol: 'OBEROIRLTY', name: 'Oberoi Realty', lotSize: 350 },
  { symbol: 'OFSS', name: 'Oracle Financial Services', lotSize: 50 },
  { symbol: 'OIL', name: 'Oil India', lotSize: 850 },
  { symbol: 'ONGC', name: 'ONGC', lotSize: 1900 },
  { symbol: 'PAGEIND', name: 'Page Industries', lotSize: 15 },
  { symbol: 'PAYTM', name: 'One97 Communications', lotSize: 850 },
  { symbol: 'PERSISTENT', name: 'Persistent Systems', lotSize: 100 },
  { symbol: 'PETRONET', name: 'Petronet LNG', lotSize: 1500 },
  { symbol: 'PFC', name: 'Power Finance Corp', lotSize: 1300 },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries', lotSize: 250 },
  { symbol: 'PIIND', name: 'PI Industries', lotSize: 150 },
  { symbol: 'PNB', name: 'Punjab National Bank', lotSize: 8000 },
  { symbol: 'POLYCAB', name: 'Polycab India', lotSize: 75 },
  { symbol: 'POWERGRID', name: 'Power Grid', lotSize: 1900 },
  { symbol: 'PVRINOX', name: 'PVR INOX', lotSize: 200 },
  { symbol: 'RAMCOCEM', name: 'The Ramco Cements', lotSize: 550 },
  { symbol: 'RBLBANK', name: 'RBL Bank', lotSize: 2500 },
  { symbol: 'RECLTD', name: 'REC', lotSize: 1000 },
  { symbol: 'RELIANCE', name: 'Reliance Industries', lotSize: 250 },
  { symbol: 'SAIL', name: 'SAIL', lotSize: 4750 },
  { symbol: 'SBICARD', name: 'SBI Cards', lotSize: 800 },
  { symbol: 'SBILIFE', name: 'SBI Life', lotSize: 375 },
  { symbol: 'SBIN', name: 'State Bank of India', lotSize: 750 },
  { symbol: 'SHREECEM', name: 'Shree Cement', lotSize: 25 },
  { symbol: 'SHRIRAMFIN', name: 'Shriram Finance', lotSize: 825 },
  { symbol: 'SIEMENS', name: 'Siemens', lotSize: 75 },
  { symbol: 'SRF', name: 'SRF', lotSize: 200 },
  { symbol: 'SUNPHARMA', name: 'Sun Pharma', lotSize: 350 },
  { symbol: 'SUNTV', name: 'Sun TV Network', lotSize: 750 },
  { symbol: 'SYNGENE', name: 'Syngene International', lotSize: 500 },
  { symbol: 'TATACHEM', name: 'Tata Chemicals', lotSize: 500 },
  { symbol: 'TATACOMM', name: 'Tata Communications', lotSize: 250 },
  { symbol: 'TATACONSUM', name: 'Tata Consumer', lotSize: 550 },
  { symbol: 'TATAELXSI', name: 'Tata Elxsi', lotSize: 50 },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', lotSize: 550 },
  { symbol: 'TATAPOWER', name: 'Tata Power', lotSize: 1350 },
  { symbol: 'TATASTEEL', name: 'Tata Steel', lotSize: 550 },
  { symbol: 'TCS', name: 'Tata Consultancy', lotSize: 150 },
  { symbol: 'TECHM', name: 'Tech Mahindra', lotSize: 600 },
  { symbol: 'TITAN', name: 'Titan', lotSize: 175 },
  { symbol: 'TORNTPHARM', name: 'Torrent Pharma', lotSize: 250 },
  { symbol: 'TORNTPOWER', name: 'Torrent Power', lotSize: 375 },
  { symbol: 'TRENT', name: 'Trent', lotSize: 100 },
  { symbol: 'TVSMOTOR', name: 'TVS Motor', lotSize: 350 },
  { symbol: 'UBL', name: 'United Breweries', lotSize: 200 },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement', lotSize: 50 },
  { symbol: 'UNIONBANK', name: 'Union Bank of India', lotSize: 4650 },
  { symbol: 'UNITDSPR', name: 'United Spirits', lotSize: 400 },
  { symbol: 'UPL', name: 'UPL', lotSize: 1300 },
  { symbol: 'VBL', name: 'Varun Beverages', lotSize: 650 },
  { symbol: 'VEDL', name: 'Vedanta', lotSize: 1150 },
  { symbol: 'VOLTAS', name: 'Voltas', lotSize: 375 },
  { symbol: 'WIPRO', name: 'Wipro', lotSize: 1500 },
  { symbol: 'YESBANK', name: 'Yes Bank', lotSize: 6200 },
  { symbol: 'ZOMATO', name: 'Zomato', lotSize: 2425 },
  { symbol: 'ZYDUSLIFE', name: 'Zydus Lifesciences', lotSize: 900 },
].sort((a, b) => a.symbol.localeCompare(b.symbol));

export const NSE_EQUITY_FO_COUNT = NSE_EQUITY_FO_WATCHLIST.length;
